export const emojiDict = [
    {id:1,
      emoji:"❤️",
      name: "Red Heart"},
    {id:2,
      emoji: "💀",
      name: "Skull"},
    {id:3,
      emoji:"😂",
      name: " Face with Tears of Joy"},
    {id:4,
     emoji:"🥺",
     name: "Pleading Face"},
    {id:5,
     emoji:"😍",
     name: "Smiling Face with Heart-Eyes"},
    {id:6,
    emoji:"😭",
    name:"Loudly Crying Face"},
    {id:7,
    emoji:"🔥",
    name: "Fire"},
    {id:8,
    emoji:"👀",
    name:"Eyes"},
    {id:9,
    emoji:"😉",
    name:"Winking Face"},
    {id:10,
    emoji:"👻",
    name:"Ghost"},
    {id:11,
    emoji:"🤔",
    name:"Thinking Face"},
    {id:12,
    emoji:"😜",
    name:"Winking Face with Tongue"},
    {id:13,
    emoji:"😴",
    name:"Sleeping Face"},
    {id:14,
    emoji:"🙄",
    name:"Face with Rolling Eyes"},
    {id:15,
    emoji:"😬",
    name:"Grimacing Face"},
    {id:16,
      emoji:"🥲",
      name:" Smiling Face with Tear"
    },
    {id:17,
      emoji:"😐",
      name:"Neutral Face"
    },
    {id:19,
      emoji:"😴",
      name:"Sleeping Face"
    },
    {id:15,
      emoji:"😟",
      name:"Worried Face"
    },
    
  
  ]